language: cpp
git:
  depth: false

matrix:
  include:
    - name: "g++ 8"
      os: linux
      dist: xenial
      python: 3.7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - cmake
            - ninja-build
      env:
        - MATRIX_EVAL="CC=/usr/bin/gcc-8 && CXX=/usr/bin/g++-8"

    - name: "clang 7"
      os: linux
      dist: xenial
      python: 3.7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libstdc++-8-dev
            - cmake
            - ninja-build
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"

before_install:
  - eval "${MATRIX_EVAL}"
  - pip install --user conan
  - $(mkdir build && cd build && conan install -s compiler.libcxx=libstdc++11 -b never ..)

script:
  - set -e
  - mkdir -p build && cd build
  - cmake -GNinja -DCMAKE_BUILD_TYPE=Release ..
  - ninja
  - ctest -j4
  - set +e

