language: cpp
compiler:
    - clang
    - gcc

git:
    depth: false

dist: xenial
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-8
    - cmake
    - ninja-build

script:
    - mkdir build
    - cd build
    - CXX=/usr/bin/g++-8 cmake -GNinja -DCMAKE_BUILD_TYPE=Release ..
    - ninja

